### ISSUE TITLE
Hide Packages & Releases 

### ISSUE THREAD

**Issue by verma-kunal** [elshadaghazade/PyProjObfuscator#1]
Suggested to hide packages and releases if not being used in the project for the time being !! 

![Screenshot 2021-06-28 at 1 21 19 PM](https://user-images.githubusercontent.com/72245772/123599884-bb1ab500-d813-11eb-9724-2eb9d94a356d.png)

**Comment by elshadaghazade** [comment]
Thank you for your report. I'm gonna close this issue and fix it.
